networks:
  avonale:
    driver: bridge

services:
  db:
    image: postgres
    restart: always
    ports:
      - 127.0.0.1:5432:5432    
    environment:
      POSTGRES_DB: avonale_db
      POSTGRES_PASSWORD: avonale123@
    volumes:
      - postgres_avonale_data:/var/lib/postgresql/data
    networks:
      - avonale
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5  

  webapi:
    image: webapi
    build:
      context: ./src/dotnet
      dockerfile: ./WebAPI.Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ConnectionStrings__ApplicationContext=User ID =postgres;Password=avonale123@;Server=db;Port=5432;Database=avonale_db;
    networks:
      - avonale
    depends_on:
      db:
        condition: service_healthy

    restart: on-failure

volumes:
 postgres_avonale_data:  
